# makefile for cargo
[config]
default_to_workspace = false

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.build_x64]
command = "cargo"
args = ["build", "${@}"]

[tasks.build_x86]
command = "cargo"
args = ["build", "-p", "azookey-windows", "--target=i686-pc-windows-msvc", "${@}"]

[tasks.build_tauri]
description = "Build the settings UI"
script_runner = "@shell"
script = """
cd frontend
npm run tauri build
"""

[tasks.build_installer]
command = "iscc"
args = ["./installer/Installer.iss"]

[tasks.post_build]
description = "Copy necessary files"
script_runner = "powershell"
script_extension = "ps1"
script  = """
$str=$args[0]
if ([string]::IsNullOrEmpty($str)) {
    $str = "debug"
} else {
    $str=$str.Substring(2)
}


mkdir build/x86 -Force

cp target/$str/ui.exe build
cp target/$str/azookey-server.exe build
cp target/$str/azookey_windows.dll build
cp target/$str/launcher.exe build


cp target/i686-pc-windows-msvc/$str/azookey_windows.dll build/x86

if (Test-Path llama_cpu) { cp -Recurse -Force llama_cpu build }
if (Test-Path llama_cuda) { cp -Recurse -Force llama_cuda build }
if (Test-Path llama_vulkan) { cp -Recurse -Force llama_vulkan build }

cp -Recurse -Force server-swift/azooKey_emoji_dictionary_storage/EmojiDictionary build
cp -Recurse -Force server-swift/azooKey_dictionary_storage/Dictionary build

if (Test-Path zenz.gguf) { cp zenz.gguf build }
"""
args = ["${@}"]

[tasks.grant_appcontainer_permissions]
description = "Grant AppContainer read and execute permissions to built IME DLLs"
script_runner = "powershell"
script_extension = "ps1"
script = """
icacls build/azookey_windows.dll /grant "*S-1-15-2-1:(RX)"
icacls build/x86/azookey_windows.dll /grant "*S-1-15-2-1:(RX)"
"""

[tasks.build]
clear = true
description = "Run the flow"
dependencies = [
    "format",
    "build_x64",
    "build_x86",
    "build_tauri",
    "post_build",
    "build_installer"
]
